#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=1.0.1

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY .daml/dist/mortgage-repackaging-2.0.0.dar \
     scripts/ledger_setup.sh \
     /home/daml/

USER root
RUN chown daml mortgage-repackaging-2.0.0.dar
USER daml

EXPOSE 6865

CMD ./ledger_setup.sh localhost 6865 ./mortgage-repackaging-2.0.0.dar Main.Main:initialize & \
    ~/.daml/bin/daml sandbox -- --address 0.0.0.0 --port 6865 mortgage-repackaging-2.0.0.dar
