#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: circleci/openjdk:11.0-jdk
  docker_buildpack:
    docker:
      - image: circleci/buildpack-deps:xenial

only-release-tags: &only-release-tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

commands:
  install_sdk:
    description: "Install the DAML SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          command: |
            ./scripts/install-daml.sh << parameters.version >>

jobs:
  daml_test:
    parameters:
      daml_sdk_version:
        type: string
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - daml-{{ checksum "daml.yaml" }}
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            daml build -o target/mortgage-repackaging.dar
            daml test --junit target/daml-test-reports/daml-test.xml --files daml/LibraryModules.daml
      - save_cache:
          paths:
            - ~/.daml
          key: daml-{{ checksum "daml.yaml" }}
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports
      - persist_to_workspace:
          root: target
          paths:
            - "*.dar"

  github_release:
    executor: docker_buildpack
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push a new github release
          command: |
            ./scripts/release.sh ex-mortgage-repackaging

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test:
          daml_sdk_version: "0.13.46"
  build_and_release:
    jobs:
      - daml_test:
          <<: *only-release-tags
          daml_sdk_version: "0.13.46"
      - github_release:
          context: github-refapp-repo-context
          requires:
            - daml_test
          <<: *only-release-tags
