#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: digitalasset/daml-sdk:0.12.15-circleci-master


jobs:
  daml_test:
    executor: daml-executor
    steps:
      - checkout
      - run:
          command: |
            mkdir -p target/daml-test-reports
            da compile
            da run -- damlc test --junit target/daml-test-reports/daml-test.xml daml/LibraryModules.daml
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test
