/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_digitalasset_ledger_api_v1_event_pb = require('../../../../../com/digitalasset/ledger/api/v1/event_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_event_pb);
var com_digitalasset_ledger_api_v1_transaction_filter_pb = require('../../../../../com/digitalasset/ledger/api/v1/transaction_filter_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_transaction_filter_pb);
var com_digitalasset_ledger_api_v1_trace_context_pb = require('../../../../../com/digitalasset/ledger/api/v1/trace_context_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_trace_context_pb);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.displayName = 'proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filter: (f = msg.getFilter()) && com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter.toObject(includeInstance, f),
    verbose: jspb.Message.getFieldWithDefault(msg, 3, false),
    traceContext: (f = msg.getTraceContext()) && com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest;
  return proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    case 2:
      var value = new com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVerbose(value);
      break;
    case 1000:
      var value = new com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.deserializeBinaryFromReader);
      msg.setTraceContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter.serializeBinaryToWriter
    );
  }
  f = message.getVerbose();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getTraceContext();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TransactionFilter filter = 2;
 * @return {?proto.com.digitalasset.ledger.api.v1.TransactionFilter}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.getFilter = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TransactionFilter} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter, 2));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TransactionFilter|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.setFilter = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.clearFilter = function() {
  this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool verbose = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.getVerbose = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.setVerbose = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional TraceContext trace_context = 1000;
 * @return {?proto.com.digitalasset.ledger.api.v1.TraceContext}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.getTraceContext = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TraceContext} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext, 1000));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TraceContext|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.setTraceContext = function(value) {
  jspb.Message.setWrapperField(this, 1000, value);
};


proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.clearTraceContext = function() {
  this.setTraceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsRequest.prototype.hasTraceContext = function() {
  return jspb.Message.getField(this, 1000) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.displayName = 'proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    offset: jspb.Message.getFieldWithDefault(msg, 1, ""),
    workflowId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    activeContractsList: jspb.Message.toObjectList(msg.getActiveContractsList(),
    com_digitalasset_ledger_api_v1_event_pb.CreatedEvent.toObject, includeInstance),
    traceContext: (f = msg.getTraceContext()) && com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse;
  return proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOffset(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 3:
      var value = new com_digitalasset_ledger_api_v1_event_pb.CreatedEvent;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_event_pb.CreatedEvent.deserializeBinaryFromReader);
      msg.addActiveContracts(value);
      break;
    case 1000:
      var value = new com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.deserializeBinaryFromReader);
      msg.setTraceContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffset();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getActiveContractsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      com_digitalasset_ledger_api_v1_event_pb.CreatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getTraceContext();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string offset = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.getOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.setOffset = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string workflow_id = 2;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.setWorkflowId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated CreatedEvent active_contracts = 3;
 * @return {!Array<!proto.com.digitalasset.ledger.api.v1.CreatedEvent>}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.getActiveContractsList = function() {
  return /** @type{!Array<!proto.com.digitalasset.ledger.api.v1.CreatedEvent>} */ (
    jspb.Message.getRepeatedWrapperField(this, com_digitalasset_ledger_api_v1_event_pb.CreatedEvent, 3));
};


/** @param {!Array<!proto.com.digitalasset.ledger.api.v1.CreatedEvent>} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.setActiveContractsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.com.digitalasset.ledger.api.v1.CreatedEvent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.digitalasset.ledger.api.v1.CreatedEvent}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.addActiveContracts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.com.digitalasset.ledger.api.v1.CreatedEvent, opt_index);
};


proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.clearActiveContractsList = function() {
  this.setActiveContractsList([]);
};


/**
 * optional TraceContext trace_context = 1000;
 * @return {?proto.com.digitalasset.ledger.api.v1.TraceContext}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.getTraceContext = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TraceContext} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext, 1000));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TraceContext|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.setTraceContext = function(value) {
  jspb.Message.setWrapperField(this, 1000, value);
};


proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.clearTraceContext = function() {
  this.setTraceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetActiveContractsResponse.prototype.hasTraceContext = function() {
  return jspb.Message.getField(this, 1000) != null;
};


goog.object.extend(exports, proto.com.digitalasset.ledger.api.v1);
