/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_digitalasset_ledger_api_v1_value_pb = require('../../../../../com/digitalasset/ledger/api/v1/value_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_value_pb);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.ArchivedEvent', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.CreatedEvent', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.Event', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.ExercisedEvent', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.digitalasset.ledger.api.v1.Event.oneofGroups_);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.Event.displayName = 'proto.com.digitalasset.ledger.api.v1.Event';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.Event.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.com.digitalasset.ledger.api.v1.Event.EventCase = {
  EVENT_NOT_SET: 0,
  CREATED: 1,
  EXERCISED: 2,
  ARCHIVED: 3
};

/**
 * @return {proto.com.digitalasset.ledger.api.v1.Event.EventCase}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.getEventCase = function() {
  return /** @type {proto.com.digitalasset.ledger.api.v1.Event.EventCase} */(jspb.Message.computeOneofCase(this, proto.com.digitalasset.ledger.api.v1.Event.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.Event} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
    created: (f = msg.getCreated()) && proto.com.digitalasset.ledger.api.v1.CreatedEvent.toObject(includeInstance, f),
    exercised: (f = msg.getExercised()) && proto.com.digitalasset.ledger.api.v1.ExercisedEvent.toObject(includeInstance, f),
    archived: (f = msg.getArchived()) && proto.com.digitalasset.ledger.api.v1.ArchivedEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.Event}
 */
proto.com.digitalasset.ledger.api.v1.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.Event;
  return proto.com.digitalasset.ledger.api.v1.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.Event}
 */
proto.com.digitalasset.ledger.api.v1.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.digitalasset.ledger.api.v1.CreatedEvent;
      reader.readMessage(value,proto.com.digitalasset.ledger.api.v1.CreatedEvent.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 2:
      var value = new proto.com.digitalasset.ledger.api.v1.ExercisedEvent;
      reader.readMessage(value,proto.com.digitalasset.ledger.api.v1.ExercisedEvent.deserializeBinaryFromReader);
      msg.setExercised(value);
      break;
    case 3:
      var value = new proto.com.digitalasset.ledger.api.v1.ArchivedEvent;
      reader.readMessage(value,proto.com.digitalasset.ledger.api.v1.ArchivedEvent.deserializeBinaryFromReader);
      msg.setArchived(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.Event} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.digitalasset.ledger.api.v1.CreatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getExercised();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.digitalasset.ledger.api.v1.ExercisedEvent.serializeBinaryToWriter
    );
  }
  f = message.getArchived();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.digitalasset.ledger.api.v1.ArchivedEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional CreatedEvent created = 1;
 * @return {?proto.com.digitalasset.ledger.api.v1.CreatedEvent}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.getCreated = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.CreatedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.digitalasset.ledger.api.v1.CreatedEvent, 1));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.CreatedEvent|undefined} value */
proto.com.digitalasset.ledger.api.v1.Event.prototype.setCreated = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.com.digitalasset.ledger.api.v1.Event.oneofGroups_[0], value);
};


proto.com.digitalasset.ledger.api.v1.Event.prototype.clearCreated = function() {
  this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ExercisedEvent exercised = 2;
 * @return {?proto.com.digitalasset.ledger.api.v1.ExercisedEvent}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.getExercised = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.ExercisedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.digitalasset.ledger.api.v1.ExercisedEvent, 2));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.ExercisedEvent|undefined} value */
proto.com.digitalasset.ledger.api.v1.Event.prototype.setExercised = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.com.digitalasset.ledger.api.v1.Event.oneofGroups_[0], value);
};


proto.com.digitalasset.ledger.api.v1.Event.prototype.clearExercised = function() {
  this.setExercised(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.hasExercised = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ArchivedEvent archived = 3;
 * @return {?proto.com.digitalasset.ledger.api.v1.ArchivedEvent}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.getArchived = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.ArchivedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.digitalasset.ledger.api.v1.ArchivedEvent, 3));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.ArchivedEvent|undefined} value */
proto.com.digitalasset.ledger.api.v1.Event.prototype.setArchived = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.com.digitalasset.ledger.api.v1.Event.oneofGroups_[0], value);
};


proto.com.digitalasset.ledger.api.v1.Event.prototype.clearArchived = function() {
  this.setArchived(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.Event.prototype.hasArchived = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.digitalasset.ledger.api.v1.CreatedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.CreatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.CreatedEvent.displayName = 'proto.com.digitalasset.ledger.api.v1.CreatedEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.CreatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.CreatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateId: (f = msg.getTemplateId()) && com_digitalasset_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    createArguments: (f = msg.getCreateArguments()) && com_digitalasset_ledger_api_v1_value_pb.Record.toObject(includeInstance, f),
    witnessPartiesList: jspb.Message.getRepeatedField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.CreatedEvent}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.CreatedEvent;
  return proto.com.digitalasset.ledger.api.v1.CreatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.CreatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.CreatedEvent}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractId(value);
      break;
    case 3:
      var value = new com_digitalasset_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setTemplateId(value);
      break;
    case 4:
      var value = new com_digitalasset_ledger_api_v1_value_pb.Record;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_value_pb.Record.deserializeBinaryFromReader);
      msg.setCreateArguments(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addWitnessParties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.CreatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.CreatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_digitalasset_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getCreateArguments();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      com_digitalasset_ledger_api_v1_value_pb.Record.serializeBinaryToWriter
    );
  }
  f = message.getWitnessPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_id = 2;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.getContractId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.setContractId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Identifier template_id = 3;
 * @return {?proto.com.digitalasset.ledger.api.v1.Identifier}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.getTemplateId = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_value_pb.Identifier, 3));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.Identifier|undefined} value */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.setTemplateId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.clearTemplateId = function() {
  this.setTemplateId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.hasTemplateId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Record create_arguments = 4;
 * @return {?proto.com.digitalasset.ledger.api.v1.Record}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.getCreateArguments = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.Record} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_value_pb.Record, 4));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.Record|undefined} value */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.setCreateArguments = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.clearCreateArguments = function() {
  this.setCreateArguments(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.hasCreateArguments = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string witness_parties = 5;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.getWitnessPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.setWitnessPartiesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.addWitnessParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.CreatedEvent.prototype.clearWitnessPartiesList = function() {
  this.setWitnessPartiesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.digitalasset.ledger.api.v1.ArchivedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.ArchivedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.ArchivedEvent.displayName = 'proto.com.digitalasset.ledger.api.v1.ArchivedEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.ArchivedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.ArchivedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateId: (f = msg.getTemplateId()) && com_digitalasset_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    witnessPartiesList: jspb.Message.getRepeatedField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.ArchivedEvent}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.ArchivedEvent;
  return proto.com.digitalasset.ledger.api.v1.ArchivedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.ArchivedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.ArchivedEvent}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractId(value);
      break;
    case 3:
      var value = new com_digitalasset_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setTemplateId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addWitnessParties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.ArchivedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.ArchivedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_digitalasset_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getWitnessPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_id = 2;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.getContractId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.setContractId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Identifier template_id = 3;
 * @return {?proto.com.digitalasset.ledger.api.v1.Identifier}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.getTemplateId = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_value_pb.Identifier, 3));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.Identifier|undefined} value */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.setTemplateId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.clearTemplateId = function() {
  this.setTemplateId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.hasTemplateId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated string witness_parties = 4;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.getWitnessPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.setWitnessPartiesList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.addWitnessParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.ArchivedEvent.prototype.clearWitnessPartiesList = function() {
  this.setWitnessPartiesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.digitalasset.ledger.api.v1.ExercisedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.ExercisedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.ExercisedEvent.displayName = 'proto.com.digitalasset.ledger.api.v1.ExercisedEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.repeatedFields_ = [7,10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.ExercisedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.ExercisedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateId: (f = msg.getTemplateId()) && com_digitalasset_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    contractCreatingEventId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    choice: jspb.Message.getFieldWithDefault(msg, 5, ""),
    choiceArgument: (f = msg.getChoiceArgument()) && com_digitalasset_ledger_api_v1_value_pb.Value.toObject(includeInstance, f),
    actingPartiesList: jspb.Message.getRepeatedField(msg, 7),
    consuming: jspb.Message.getFieldWithDefault(msg, 8, false),
    witnessPartiesList: jspb.Message.getRepeatedField(msg, 10),
    childEventIdsList: jspb.Message.getRepeatedField(msg, 11)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.ExercisedEvent}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.ExercisedEvent;
  return proto.com.digitalasset.ledger.api.v1.ExercisedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.ExercisedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.ExercisedEvent}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractId(value);
      break;
    case 3:
      var value = new com_digitalasset_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setTemplateId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractCreatingEventId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setChoice(value);
      break;
    case 6:
      var value = new com_digitalasset_ledger_api_v1_value_pb.Value;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_value_pb.Value.deserializeBinaryFromReader);
      msg.setChoiceArgument(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addActingParties(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConsuming(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addWitnessParties(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addChildEventIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.ExercisedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.ExercisedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_digitalasset_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getContractCreatingEventId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getChoice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getChoiceArgument();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      com_digitalasset_ledger_api_v1_value_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getActingPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getConsuming();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getWitnessPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getChildEventIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_id = 2;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getContractId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setContractId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Identifier template_id = 3;
 * @return {?proto.com.digitalasset.ledger.api.v1.Identifier}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getTemplateId = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_value_pb.Identifier, 3));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.Identifier|undefined} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setTemplateId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.clearTemplateId = function() {
  this.setTemplateId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.hasTemplateId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string contract_creating_event_id = 4;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getContractCreatingEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setContractCreatingEventId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string choice = 5;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getChoice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setChoice = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Value choice_argument = 6;
 * @return {?proto.com.digitalasset.ledger.api.v1.Value}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getChoiceArgument = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.Value} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_value_pb.Value, 6));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.Value|undefined} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setChoiceArgument = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.clearChoiceArgument = function() {
  this.setChoiceArgument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.hasChoiceArgument = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated string acting_parties = 7;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getActingPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setActingPartiesList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.addActingParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.clearActingPartiesList = function() {
  this.setActingPartiesList([]);
};


/**
 * optional bool consuming = 8;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getConsuming = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 8, false));
};


/** @param {boolean} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setConsuming = function(value) {
  jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * repeated string witness_parties = 10;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getWitnessPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setWitnessPartiesList = function(value) {
  jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.addWitnessParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.clearWitnessPartiesList = function() {
  this.setWitnessPartiesList([]);
};


/**
 * repeated string child_event_ids = 11;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.getChildEventIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.setChildEventIdsList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.addChildEventIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.ExercisedEvent.prototype.clearChildEventIdsList = function() {
  this.setChildEventIdsList([]);
};


goog.object.extend(exports, proto.com.digitalasset.ledger.api.v1);
