/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_digitalasset_ledger_api_v1_ledger_offset_pb = require('../../../../../com/digitalasset/ledger/api/v1/ledger_offset_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_ledger_offset_pb);
var com_digitalasset_ledger_api_v1_transaction_filter_pb = require('../../../../../com/digitalasset/ledger/api/v1/transaction_filter_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_transaction_filter_pb);
var com_digitalasset_ledger_api_v1_transaction_pb = require('../../../../../com/digitalasset/ledger/api/v1/transaction_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_transaction_pb);
var com_digitalasset_ledger_api_v1_trace_context_pb = require('../../../../../com/digitalasset/ledger/api/v1/trace_context_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_trace_context_pb);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetTransactionResponse', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.displayName = 'proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    begin: (f = msg.getBegin()) && com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.toObject(includeInstance, f),
    filter: (f = msg.getFilter()) && com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter.toObject(includeInstance, f),
    verbose: jspb.Message.getFieldWithDefault(msg, 5, false),
    traceContext: (f = msg.getTraceContext()) && com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest;
  return proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    case 2:
      var value = new com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.deserializeBinaryFromReader);
      msg.setBegin(value);
      break;
    case 3:
      var value = new com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    case 4:
      var value = new com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVerbose(value);
      break;
    case 1000:
      var value = new com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.deserializeBinaryFromReader);
      msg.setTraceContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBegin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.serializeBinaryToWriter
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter.serializeBinaryToWriter
    );
  }
  f = message.getVerbose();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getTraceContext();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional LedgerOffset begin = 2;
 * @return {?proto.com.digitalasset.ledger.api.v1.LedgerOffset}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.getBegin = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.LedgerOffset} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset, 2));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.LedgerOffset|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.setBegin = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.clearBegin = function() {
  this.setBegin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.hasBegin = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional LedgerOffset end = 3;
 * @return {?proto.com.digitalasset.ledger.api.v1.LedgerOffset}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.getEnd = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.LedgerOffset} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset, 3));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.LedgerOffset|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.setEnd = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.clearEnd = function() {
  this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional TransactionFilter filter = 4;
 * @return {?proto.com.digitalasset.ledger.api.v1.TransactionFilter}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.getFilter = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TransactionFilter} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_transaction_filter_pb.TransactionFilter, 4));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TransactionFilter|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.setFilter = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.clearFilter = function() {
  this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool verbose = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.getVerbose = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.setVerbose = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional TraceContext trace_context = 1000;
 * @return {?proto.com.digitalasset.ledger.api.v1.TraceContext}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.getTraceContext = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TraceContext} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext, 1000));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TraceContext|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.setTraceContext = function(value) {
  jspb.Message.setWrapperField(this, 1000, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.clearTraceContext = function() {
  this.setTraceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsRequest.prototype.hasTraceContext = function() {
  return jspb.Message.getField(this, 1000) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.displayName = 'proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    com_digitalasset_ledger_api_v1_transaction_pb.Transaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse;
  return proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_digitalasset_ledger_api_v1_transaction_pb.Transaction;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_transaction_pb.Transaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      com_digitalasset_ledger_api_v1_transaction_pb.Transaction.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Transaction transactions = 1;
 * @return {!Array<!proto.com.digitalasset.ledger.api.v1.Transaction>}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.com.digitalasset.ledger.api.v1.Transaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, com_digitalasset_ledger_api_v1_transaction_pb.Transaction, 1));
};


/** @param {!Array<!proto.com.digitalasset.ledger.api.v1.Transaction>} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.prototype.setTransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.digitalasset.ledger.api.v1.Transaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.digitalasset.ledger.api.v1.Transaction}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.digitalasset.ledger.api.v1.Transaction, opt_index);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionsResponse.prototype.clearTransactionsList = function() {
  this.setTransactionsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.displayName = 'proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse;
  return proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TransactionTree transactions = 1;
 * @return {!Array<!proto.com.digitalasset.ledger.api.v1.TransactionTree>}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.com.digitalasset.ledger.api.v1.TransactionTree>} */ (
    jspb.Message.getRepeatedWrapperField(this, com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree, 1));
};


/** @param {!Array<!proto.com.digitalasset.ledger.api.v1.TransactionTree>} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.prototype.setTransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.digitalasset.ledger.api.v1.TransactionTree=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.digitalasset.ledger.api.v1.TransactionTree}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.digitalasset.ledger.api.v1.TransactionTree, opt_index);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionTreesResponse.prototype.clearTransactionsList = function() {
  this.setTransactionsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.displayName = 'proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    eventId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    requestingPartiesList: jspb.Message.getRepeatedField(msg, 3),
    traceContext: (f = msg.getTraceContext()) && com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest;
  return proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addRequestingParties(value);
      break;
    case 1000:
      var value = new com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.deserializeBinaryFromReader);
      msg.setTraceContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRequestingPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getTraceContext();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string event_id = 2;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string requesting_parties = 3;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.getRequestingPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.setRequestingPartiesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.addRequestingParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.clearRequestingPartiesList = function() {
  this.setRequestingPartiesList([]);
};


/**
 * optional TraceContext trace_context = 1000;
 * @return {?proto.com.digitalasset.ledger.api.v1.TraceContext}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.getTraceContext = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TraceContext} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext, 1000));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TraceContext|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.setTraceContext = function(value) {
  jspb.Message.setWrapperField(this, 1000, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.clearTraceContext = function() {
  this.setTraceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByEventIdRequest.prototype.hasTraceContext = function() {
  return jspb.Message.getField(this, 1000) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.displayName = 'proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    transactionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    requestingPartiesList: jspb.Message.getRepeatedField(msg, 3),
    traceContext: (f = msg.getTraceContext()) && com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest;
  return proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addRequestingParties(value);
      break;
    case 1000:
      var value = new com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.deserializeBinaryFromReader);
      msg.setTraceContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRequestingPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getTraceContext();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string transaction_id = 2;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.setTransactionId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string requesting_parties = 3;
 * @return {!Array<string>}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.getRequestingPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.setRequestingPartiesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.addRequestingParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.clearRequestingPartiesList = function() {
  this.setRequestingPartiesList([]);
};


/**
 * optional TraceContext trace_context = 1000;
 * @return {?proto.com.digitalasset.ledger.api.v1.TraceContext}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.getTraceContext = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TraceContext} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext, 1000));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TraceContext|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.setTraceContext = function(value) {
  jspb.Message.setWrapperField(this, 1000, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.clearTraceContext = function() {
  this.setTraceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionByIdRequest.prototype.hasTraceContext = function() {
  return jspb.Message.getField(this, 1000) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.displayName = 'proto.com.digitalasset.ledger.api.v1.GetTransactionResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transaction: (f = msg.getTransaction()) && com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetTransactionResponse;
  return proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetTransactionResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree.serializeBinaryToWriter
    );
  }
};


/**
 * optional TransactionTree transaction = 1;
 * @return {?proto.com.digitalasset.ledger.api.v1.TransactionTree}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.prototype.getTransaction = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TransactionTree} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_transaction_pb.TransactionTree, 1));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TransactionTree|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.prototype.setTransaction = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.prototype.clearTransaction = function() {
  this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetTransactionResponse.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.displayName = 'proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    traceContext: (f = msg.getTraceContext()) && com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest;
  return proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    case 1000:
      var value = new com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.deserializeBinaryFromReader);
      msg.setTraceContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTraceContext();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TraceContext trace_context = 1000;
 * @return {?proto.com.digitalasset.ledger.api.v1.TraceContext}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.getTraceContext = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.TraceContext} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_trace_context_pb.TraceContext, 1000));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.TraceContext|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.setTraceContext = function(value) {
  jspb.Message.setWrapperField(this, 1000, value);
};


proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.clearTraceContext = function() {
  this.setTraceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndRequest.prototype.hasTraceContext = function() {
  return jspb.Message.getField(this, 1000) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.displayName = 'proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    offset: (f = msg.getOffset()) && com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse;
  return proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.deserializeBinaryFromReader);
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffset();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset.serializeBinaryToWriter
    );
  }
};


/**
 * optional LedgerOffset offset = 1;
 * @return {?proto.com.digitalasset.ledger.api.v1.LedgerOffset}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.prototype.getOffset = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.LedgerOffset} */ (
    jspb.Message.getWrapperField(this, com_digitalasset_ledger_api_v1_ledger_offset_pb.LedgerOffset, 1));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.LedgerOffset|undefined} value */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.prototype.setOffset = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.prototype.clearOffset = function() {
  this.setOffset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.GetLedgerEndResponse.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.com.digitalasset.ledger.api.v1);
