/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_digitalasset_ledger_api_v1_value_pb = require('../../../../../com/digitalasset/ledger/api/v1/value_pb.js');
goog.object.extend(proto, com_digitalasset_ledger_api_v1_value_pb);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.Filters', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.InclusiveFilters', null, global);
goog.exportSymbol('proto.com.digitalasset.ledger.api.v1.TransactionFilter', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.TransactionFilter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.TransactionFilter.displayName = 'proto.com.digitalasset.ledger.api.v1.TransactionFilter';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.TransactionFilter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.TransactionFilter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.toObject = function(includeInstance, msg) {
  var f, obj = {
    filtersByPartyMap: (f = msg.getFiltersByPartyMap()) ? f.toObject(includeInstance, proto.com.digitalasset.ledger.api.v1.Filters.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.TransactionFilter}
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.TransactionFilter;
  return proto.com.digitalasset.ledger.api.v1.TransactionFilter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.TransactionFilter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.TransactionFilter}
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getFiltersByPartyMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.digitalasset.ledger.api.v1.Filters.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.TransactionFilter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.TransactionFilter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFiltersByPartyMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.digitalasset.ledger.api.v1.Filters.serializeBinaryToWriter);
  }
};


/**
 * map<string, Filters> filters_by_party = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.digitalasset.ledger.api.v1.Filters>}
 */
proto.com.digitalasset.ledger.api.v1.TransactionFilter.prototype.getFiltersByPartyMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.digitalasset.ledger.api.v1.Filters>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.com.digitalasset.ledger.api.v1.Filters));
};


proto.com.digitalasset.ledger.api.v1.TransactionFilter.prototype.clearFiltersByPartyMap = function() {
  this.getFiltersByPartyMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.Filters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.Filters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.Filters.displayName = 'proto.com.digitalasset.ledger.api.v1.Filters';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.Filters.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.Filters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.Filters} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.Filters.toObject = function(includeInstance, msg) {
  var f, obj = {
    inclusive: (f = msg.getInclusive()) && proto.com.digitalasset.ledger.api.v1.InclusiveFilters.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.Filters}
 */
proto.com.digitalasset.ledger.api.v1.Filters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.Filters;
  return proto.com.digitalasset.ledger.api.v1.Filters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.Filters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.Filters}
 */
proto.com.digitalasset.ledger.api.v1.Filters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.digitalasset.ledger.api.v1.InclusiveFilters;
      reader.readMessage(value,proto.com.digitalasset.ledger.api.v1.InclusiveFilters.deserializeBinaryFromReader);
      msg.setInclusive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.Filters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.Filters.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.Filters} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.Filters.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInclusive();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.digitalasset.ledger.api.v1.InclusiveFilters.serializeBinaryToWriter
    );
  }
};


/**
 * optional InclusiveFilters inclusive = 1;
 * @return {?proto.com.digitalasset.ledger.api.v1.InclusiveFilters}
 */
proto.com.digitalasset.ledger.api.v1.Filters.prototype.getInclusive = function() {
  return /** @type{?proto.com.digitalasset.ledger.api.v1.InclusiveFilters} */ (
    jspb.Message.getWrapperField(this, proto.com.digitalasset.ledger.api.v1.InclusiveFilters, 1));
};


/** @param {?proto.com.digitalasset.ledger.api.v1.InclusiveFilters|undefined} value */
proto.com.digitalasset.ledger.api.v1.Filters.prototype.setInclusive = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.digitalasset.ledger.api.v1.Filters.prototype.clearInclusive = function() {
  this.setInclusive(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.digitalasset.ledger.api.v1.Filters.prototype.hasInclusive = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.digitalasset.ledger.api.v1.InclusiveFilters.repeatedFields_, null);
};
goog.inherits(proto.com.digitalasset.ledger.api.v1.InclusiveFilters, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.digitalasset.ledger.api.v1.InclusiveFilters.displayName = 'proto.com.digitalasset.ledger.api.v1.InclusiveFilters';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.prototype.toObject = function(opt_includeInstance) {
  return proto.com.digitalasset.ledger.api.v1.InclusiveFilters.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.digitalasset.ledger.api.v1.InclusiveFilters} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.toObject = function(includeInstance, msg) {
  var f, obj = {
    templateIdsList: jspb.Message.toObjectList(msg.getTemplateIdsList(),
    com_digitalasset_ledger_api_v1_value_pb.Identifier.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.digitalasset.ledger.api.v1.InclusiveFilters}
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.digitalasset.ledger.api.v1.InclusiveFilters;
  return proto.com.digitalasset.ledger.api.v1.InclusiveFilters.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.digitalasset.ledger.api.v1.InclusiveFilters} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.digitalasset.ledger.api.v1.InclusiveFilters}
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_digitalasset_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_digitalasset_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.addTemplateIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.digitalasset.ledger.api.v1.InclusiveFilters.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.digitalasset.ledger.api.v1.InclusiveFilters} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTemplateIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      com_digitalasset_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Identifier template_ids = 1;
 * @return {!Array<!proto.com.digitalasset.ledger.api.v1.Identifier>}
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.prototype.getTemplateIdsList = function() {
  return /** @type{!Array<!proto.com.digitalasset.ledger.api.v1.Identifier>} */ (
    jspb.Message.getRepeatedWrapperField(this, com_digitalasset_ledger_api_v1_value_pb.Identifier, 1));
};


/** @param {!Array<!proto.com.digitalasset.ledger.api.v1.Identifier>} value */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.prototype.setTemplateIdsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.digitalasset.ledger.api.v1.Identifier=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.digitalasset.ledger.api.v1.Identifier}
 */
proto.com.digitalasset.ledger.api.v1.InclusiveFilters.prototype.addTemplateIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.digitalasset.ledger.api.v1.Identifier, opt_index);
};


proto.com.digitalasset.ledger.api.v1.InclusiveFilters.prototype.clearTemplateIdsList = function() {
  this.setTemplateIdsList([]);
};


goog.object.extend(exports, proto.com.digitalasset.ledger.api.v1);
